# docker build -t imgname .
# docker run --name contname -d -p 8081:80 imgname
# http://localhost:8081/
# See 'api-dir' for available resources e.g:
# http://localhost:8081/obj
# http://localhost:8081/ob2
FROM nginx
COPY ./api-dir /usr/share/nginx/html